defaultSemverRangePrefix: ""

logFilters:
  - code: YN0002
    level: error
  - code: YN0060
    level: error
  - code: YN0068
    level: error
  - code: YN0086
    level: error

# Fix missing peer dep declarations in @visx/visx 4.0.1-alpha.0
# @visx/visx and @visx/xychart don't declare react-dom in their peer deps,
# and @visx/visx doesn't forward @react-spring/web (used optionally by @visx/xychart
# for animations; we don't use @visx/xychart so it is marked optional here).
packageExtensions:
  "@visx/visx@*":
    peerDependencies:
      react-dom: "^16.14.0 || ^17.0.0-0 || ^18.0.0-0 || ^19.0.0-0"
      "@react-spring/web": "^9.7.5 || ^10.0.0"
  "@visx/xychart@*":
    peerDependencies:
      react-dom: "^16.14.0 || ^17.0.0-0 || ^18.0.0-0 || ^19.0.0-0"

# Fix missing typescript peer dep declarations in vercel@50.25.4
  "vercel@*":
    peerDependencies:
      typescript: ">=4.9.5"
  "@vercel/express@*":
    peerDependencies:
      typescript: ">=4.9.5"

nodeLinker: node-modules
