import type EM from '@/data/em.json';
import type EMML from '@/data/em-ml.json';
import type IC from '@/data/ic.json';
import type ICMML from '@/data/ic-ml.json';

type EMKeys = keyof typeof EM;
type ICKeys = keyof typeof IC;
type EMMLKeys = keyof typeof EMML;
type ICMMLKeys = keyof typeof ICMML;
type EMDetails = (typeof EM)[EMKeys];
type ICDetails = (typeof IC)[ICKeys];
type EMMLDetails = (typeof EMML)[EMMLKeys];
type ICMMLDetails = (typeof ICMML)[ICMMLKeys];
type ICRecord = Record<ICKeys, ICDetails>;
type EMRecord = Record<EMKeys, EMDetails>;
type EMMLRecord = Record<EMMLKeys, EMMLDetails>;
type ICMMLRecord = Record<ICMMLKeys, ICMMLDetails>;
export type LevelRecord = ICRecord | EMRecord | EMMLRecord | ICMMLRecord;
export type LevelKeys = EMKeys | ICKeys | EMMLKeys | ICMMLKeys;
export type LevelDetails = EMDetails | ICDetails | EMMLDetails | ICMMLDetails;
